"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Role = "student" | "teacher" | "admin";
type State = "pending" | "confirmed" | "rejected" | "cancelled";
type Profile = { id:string; identity_no:string; full_name:string; role:Role; cohort:string|null; active:boolean };
type Teacher = { profile_id:string; active:boolean; forced_capacity:number|null; calculated_capacity:number; profile:Profile; occupied:number };
type Request = { id:string; student_id:string; teacher_id:string; origin:"student"|"teacher"; state:State; created_at:string };
const TOTAL = 163;

function Badge({ state }: {state:State}) { const t:Record<State,string>={pending:"等待确认",confirmed:"已确认",rejected:"已拒绝",cancelled:"已撤回"}; return <span className={`badge badge-${state}`}>{t[state]}</span>; }
function message(error: unknown) { return error instanceof Error ? error.message : "操作未完成，请稍后重试。"; }

export default function Home() {
  const [me,setMe]=useState<Profile|null>(null); const [people,setPeople]=useState<Profile[]>([]); const [teachers,setTeachers]=useState<Teacher[]>([]); const [requests,setRequests]=useState<Request[]>([]);
  const [identity,setIdentity]=useState(""); const [password,setPassword]=useState(""); const [notice,setNotice]=useState("请使用学号、工号或管理员编号登录。"); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [invite,setInvite]=useState(""); const [forced,setForced]=useState<Record<string,string>>({});
  async function refresh() {
    const {data:{user}}=await supabase.auth.getUser(); if(!user){setMe(null);setPeople([]);setTeachers([]);setRequests([]);setLoading(false);return;}
    setLoading(true); const [mine,all,ts,rs]=await Promise.all([
      supabase.from("profiles").select("id,identity_no,full_name,role,cohort,active").eq("id",user.id).maybeSingle(),
      supabase.from("profiles").select("id,identity_no,full_name,role,cohort,active").eq("active",true),
      supabase.from("teachers").select("profile_id,active,forced_capacity,calculated_capacity").eq("active",true),
      supabase.from("selection_requests").select("id,student_id,teacher_id,origin,state,created_at").order("created_at",{ascending:false})
    ]); if(mine.error||!mine.data){setNotice("找不到你的系统账户。请联系管理员导入名单后再登录。");setLoading(false);return;} if(all.error||ts.error||rs.error){setNotice(message(all.error||ts.error||rs.error));setLoading(false);return;}
    const ps=(all.data??[]) as Profile[], req=(rs.data??[]) as Request[], map=new Map(ps.map(x=>[x.id,x])); setMe(mine.data as Profile);setPeople(ps);setRequests(req);setTeachers(((ts.data??[]) as Omit<Teacher,"profile"|"occupied">[]).flatMap(t=>{const p=map.get(t.profile_id);return p?[{...t,profile:p,occupied:req.filter(r=>r.teacher_id===t.profile_id&&(r.state==="pending"||r.state==="confirmed")).length}]:[]}));setLoading(false);
  }
  useEffect(()=>{void refresh();const {data}=supabase.auth.onAuthStateChange(()=>void refresh());return()=>data.subscription.unsubscribe();},[]);
  useEffect(()=>{if(!me)return;const ch=supabase.channel("selection-live").on("postgres_changes",{event:"*",schema:"public",table:"selection_requests"},()=>void refresh()).on("postgres_changes",{event:"*",schema:"public",table:"teachers"},()=>void refresh()).subscribe();return()=>{void supabase.removeChannel(ch);};},[me?.id]);
  const lookup=useMemo(()=>new Map(people.map(x=>[x.id,x])),[people]); const active=me?.role==="student"?requests.find(r=>r.student_id===me.id&&(r.state==="pending"||r.state==="confirmed")):undefined; const mineTeacher=teachers.find(t=>t.profile_id===me?.id); const pending=me?requests.filter(r=>r.state==="pending"&&((me.role==="teacher"&&r.teacher_id===me.id&&r.origin==="student")||(me.role==="student"&&r.student_id===me.id&&r.origin==="teacher"))):[]; const candidates=me?.role==="teacher"?people.filter(p=>p.role==="student"&&!requests.some(r=>r.student_id===p.id&&(r.state==="pending"||r.state==="confirmed"))):[];
  async function login(e:FormEvent){e.preventDefault();if(!identity.trim()||!password){setNotice("请填写账号和密码。");return;}setBusy(true);const {error}=await supabase.auth.signInWithPassword({email:`${identity.trim().toLowerCase()}@selection.local`,password});setBusy(false);setNotice(error?"登录失败：请核对账号、密码或联系管理员。":"登录成功，正在载入数据。");}
  async function call(fn:string,args:Record<string,unknown>,success:string){setBusy(true);const {error}=await supabase.rpc(fn,args);setBusy(false);if(error)setNotice(error.message);else{setNotice(success);await refresh();}}
  if(loading)return <main><header className="topbar"><span className="brand"><span className="brand-mark">选</span>毕业论文双选中心</span></header><p className="notice">正在连接系统…</p></main>;
  if(!me)return <main><header className="topbar"><span className="brand"><span className="brand-mark">选</span>毕业论文双选中心</span><span className="topbar-meta">2026届</span></header><section className="hero"><div><p className="eyebrow">论文指导 · 双向确认</p><h1>双选关系，要由双方确认。</h1><p className="lead">账户由学院根据名单统一导入。</p></div><div className="hero-stat"><strong>{TOTAL}</strong><span>A23、Z25 毕业论文名单</span><small>25 名教师参与均分</small></div></section><section className="login-panel"><p className="eyebrow">系统登录</p><h2>登录双选中心</h2><form className="login-form" onSubmit={login}><label>学号 / 工号 / 管理员编号<input value={identity} onChange={e=>setIdentity(e.target.value)} placeholder="例如 2023210109108"/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="初始密码"/></label><button className="primary" disabled={busy}>{busy?"正在登录…":"登录"}</button></form><p className="notice">{notice}</p></section></main>;
  const title=me.role==="student"?"学生账户":me.role==="teacher"?"教师工作台":"管理员控制台";
  return <main><header className="topbar"><span className="brand"><span className="brand-mark">选</span>毕业论文双选中心</span><div className="topbar-meta"><span className="live-dot"/>实时同步 <span className="divider"/>{me.full_name} · {title}<button className="text-button" onClick={()=>void supabase.auth.signOut()}>退出</button></div></header><section className="hero"><div><p className="eyebrow">论文指导 · 双向确认</p><h1>{me.role==="admin"?"名额配置，始终实时均衡。":"双选关系，要由双方确认。"}</h1><p className="lead">待确认申请同样锁定名额；拒绝后才会释放。</p></div><div className="hero-stat"><strong>{TOTAL}</strong><span>A23、Z25 毕业论文名单</span><small>{teachers.length} 名在职教师</small></div></section><p className="notice">{notice}</p>
  {me.role==="student"&&<section className="layout"><aside className="profile-card"><div className="avatar">{me.full_name[0]}</div><p className="muted">学生账户</p><h2>{me.full_name}</h2><p>{me.identity_no} · {me.cohort??"未分组"}</p><div className="rule-box">每位学生仅能保留一条待确认或已确认的双选关系。</div></aside><div><div className="section-heading"><div><p className="eyebrow">选择导师</p><h2>可申请的教师</h2></div><span>{teachers.filter(t=>t.occupied<t.calculated_capacity).length} 位尚有名额</span></div><div className="teacher-grid">{teachers.map(t=>{const left=Math.max(0,t.calculated_capacity-t.occupied);return <article className="teacher-card" key={t.profile_id}><div><div className="mini-avatar">{t.profile.full_name[0]}</div><h3>{t.profile.full_name}</h3><p>{t.forced_capacity===null?"自动均分容量":"强制容量"}</p></div><div className="capacity"><strong>{left}</strong><span>/ {t.calculated_capacity} 个可用</span></div><div className="meter"><i style={{width:`${t.calculated_capacity?t.occupied/t.calculated_capacity*100:0}%`}}/></div><button className="secondary" disabled={busy||!!active||left===0} onClick={()=>void call("create_selection_request",{target_teacher_id:t.profile_id},`已向${t.profile.full_name}发送申请，名额已锁定。`)}>{left===0?"名额已满":active?"已有申请":"申请该教师"}</button></article>})}</div></div><aside className="inbox"><p className="eyebrow">我的进度</p><h2>双选申请</h2>{requests.filter(r=>r.student_id===me.id).map(r=><div className="request" key={r.id}><Badge state={r.state}/><strong>{lookup.get(r.teacher_id)?.full_name??"教师"}</strong></div>)}{pending.map(r=><div className="request" key={r.id}><strong>{lookup.get(r.teacher_id)?.full_name} 邀请你</strong><div className="actions"><button className="secondary" onClick={()=>void call("decide_selection_request",{request_id:r.id,accept_request:false},"已拒绝申请，名额已经释放。")}>拒绝</button><button className="primary" onClick={()=>void call("decide_selection_request",{request_id:r.id,accept_request:true},"已确认双选关系。")}>确认</button></div></div>)}</aside></section>}
  {me.role==="teacher"&&<section className="teacher-workspace"><div className="section-heading"><div><p className="eyebrow">教师工作台</p><h2>待你确认的申请</h2></div><span>剩余 {Math.max(0,(mineTeacher?.calculated_capacity??0)-(mineTeacher?.occupied??0))} 个名额</span></div><div className="request-list">{pending.map(r=><article className="request-row" key={r.id}><div><h3>{lookup.get(r.student_id)?.full_name}</h3><p>{lookup.get(r.student_id)?.identity_no} · 由学生发起</p></div><Badge state="pending"/><div className="actions"><button className="secondary" onClick={()=>void call("decide_selection_request",{request_id:r.id,accept_request:false},"已拒绝申请。")}>拒绝</button><button className="primary" onClick={()=>void call("decide_selection_request",{request_id:r.id,accept_request:true},"已确认接收。")}>确认接收</button></div></article>)}<div className="teacher-apply"><h3>主动选择学生</h3><select value={invite} onChange={e=>setInvite(e.target.value)}><option value="">选择无占用关系的学生</option>{candidates.map(s=><option key={s.id} value={s.id}>{s.full_name} · {s.identity_no}</option>)}</select><button className="secondary" disabled={busy||!invite} onClick={()=>void call("teacher_invite_student",{target_student_id:invite},"邀请已发送，名额已锁定。")}>发送邀请</button></div></div></section>}
  {me.role==="admin"&&<section className="admin-workspace"><div className="section-heading"><div><p className="eyebrow">管理员控制台</p><h2>教师与容量配置</h2></div><span>{teachers.length} 位在职教师 · 163 个论文名额</span></div><div className="allocation-note"><strong>自动分配规则：</strong>先扣除强制名额，再将其余名额均分给未强制设定的在职教师。</div><div className="admin-table"><div className="table-head"><span>教师</span><span>已占用</span><span>最终容量</span><span>强制名额</span><span>操作</span></div>{teachers.map(t=><div className="table-row" key={t.profile_id}><strong>{t.profile.full_name}</strong><span>{t.occupied}</span><span>{t.calculated_capacity}</span><label className="compact-input"><input type="number" min="0" value={forced[t.profile_id]??(t.forced_capacity??"")} onChange={e=>setForced(v=>({...v,[t.profile_id]:e.target.value}))}/><button disabled={busy} onClick={()=>{const v=forced[t.profile_id];void call("set_teacher_forced_capacity",{target_teacher_id:t.profile_id,new_capacity:v===undefined||v===""?null:Number(v)},"容量已更新并重新均分。")}}>保存</button></label><button className="text-button" disabled={busy||t.occupied>0} onClick={()=>void call("set_teacher_active",{target_teacher_id:t.profile_id,new_active:false},"教师已停用，名额已重算。")}>停用</button></div>)}</div></section>}<footer>毕业论文双选中心 · 数据由学院名单统一维护</footer></main>;
}
